name: Blog of Shahbaz Chaudhary
markdown: redcarpet
paginate: 10 # pagination basted on number of posts
#exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
