name: Blog of Shahbaz Chaudhary
description: Posts about financial and trading software and other experiments
url: http://falconair.github.io/
markdown: redcarpet
paginate: 10 # pagination basted on number of posts
#exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
jobnotice: true
